/*
 * Copyright 2017-present, Yudong (Dom) Wang
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var APIDATA = {
  "api_description" : {
    "title" : "RESTful API",
    "summary" : "This RESTful API document is generated by <a class=\"wistool\" href=\"https://github.com/Wisdom-Projects/rest-client\">Wisdom RESTClient."
  },
  "api_list" : [ {
    "api_summary" : {
      "title" : "Create api",
      "method" : "POST",
      "path" : "/api"
    },
    "api_request" : {
      "header" : "Content-Type : application/json; charset=UTF-8\r\nAccept : application/json,application/xml,application/xhtml+xml,text/html,text/xml,text/plain\r\n",
      "model" : "   duration [number]\r\n   force [string]\r\n   text [object]\r\n    &#9500;&#9472;&#9472;textstring [string]\r\n    &#9500;&#9472;&#9472;color [object]\r\n    &#9474;   &#9500;&#9472;&#9472;r [string]\r\n    &#9474;   &#9500;&#9472;&#9472;g [string]\r\n    &#9474;   &#9500;&#9472;&#9472;b [string]\r\n    &#9500;&#9472;&#9472;font [string]\r\n    &#9500;&#9472;&#9472;position [object]\r\n    &#9474;   &#9500;&#9472;&#9472;x [string]\r\n    &#9474;   &#9500;&#9472;&#9472;y [string]\r\n   bitmapID [object]\r\n    &#9500;&#9472;&#9472;name [string]\r\n    &#9500;&#9472;&#9472;position [object]\r\n    &#9474;   &#9500;&#9472;&#9472;x [string]\r\n    &#9474;   &#9500;&#9472;&#9472;y [string]\r\n",
      "example" : "{\n  &quot;duration&quot;: 6,\n  &quot;force&quot;: &quot;true&quot;,\n  &quot;text&quot;: {\n    &quot;textstring&quot;: &quot;3&quot;,\n    &quot;color&quot;: {\n      &quot;r&quot;: &quot;255&quot;,\n      &quot;g&quot;: &quot;255&quot;,\n      &quot;b&quot;: &quot;255&quot;\n    },\n    &quot;font&quot;: &quot;big&quot;,\n    &quot;position&quot;: {\n      &quot;x&quot;: &quot;9&quot;,\n      &quot;y&quot;: &quot;1&quot;\n    }\n  },\n  &quot;bitmapID&quot;: {\n    &quot;name&quot;: &quot;Pika&quot;,\n    &quot;position&quot;: {\n      &quot;x&quot;: &quot;1&quot;,\n      &quot;y&quot;: &quot;0&quot;\n    }\n  }\n}"
    },
    "api_response" : [ {
      "status" : "HTTP/1.1 200 ",
      "code" : 200,
      "message" : "OK",
      "model" : "N/A",
      "example" : "N/A"
    } ]
  } ]
};
